WebApplication1/Controllers/LoginController.cs
using Dto;
using Microsoft.AspNetCore.Mvc;
using Servicios;
using WebApplication1.Exceptions;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        private IServicioLogin<LoginDto, LoginOutDto> _servicio;
        public LoginController(IServicioLogin<LoginDto, LoginOutDto> servicio)
        {
            _servicio = servicio;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Loginfail()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("email");
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Login(LoginDto loginDto)
        {

            try
            {
                LoginOutDto loginOutDto = _servicio.Login(loginDto);
                HttpContext.Session.SetString("email", loginOutDto.email);
                HttpContext.Session.SetString("token", loginOutDto.token);
            }
            catch (LoginException loginException)
            {
                return RedirectToAction("Loginfail");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication1/Controllers/MovimientoDeStockController.cs
using Dto;
using HttpAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using Models;
using Servicios;
using System.Reflection;

namespace WebApplication1.Controllers
{
    public class MovimientoDeStockController : Controller
    {
        private readonly IServicioArticulo _servicioArticulo;
        private readonly IServicioTipoDeMovimiento _servicioTipoDeMovimiento;
        private readonly IServicioMovimientoDeStock _servicioMovimientoDeStock;

        public MovimientoDeStockController(IServicioArticulo servicioArticulo, IServicioTipoDeMovimiento servicioTipoDeMovimiento, IServicioMovimientoDeStock servicioMovimientoDeStock)
        {
            _servicioArticulo = servicioArticulo;
            _servicioTipoDeMovimiento = servicioTipoDeMovimiento;
            _servicioMovimientoDeStock = servicioMovimientoDeStock;
        }

        [HttpGet]
        public IActionResult Crear()
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return View("NoAutorizado");
            }
            ViewBag.Articulos = _servicioArticulo.GetAll().Articulos;
            ViewBag.TiposDeMovimiento = _servicioTipoDeMovimiento.GetAll().Tipos;
            foreach (Articulo a in ViewBag.Articulos)
            {
                Console.WriteLine(a.id);
            }
            
            return View(new MovimientoDeStockViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(MovimientoDeStockViewModel model)
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return View("NoAutorizado");
            }

            try
            {
                var movimientoDto = new MovimientoDeStock
                {
                    FechaYHora = DateTime.Now,
                    ArticuloId = model.ArticuloId,
                    TipoDeMovimientoId = model.TipoDeMovimientoId,
                    MailUsuario = HttpContext.Session.GetString("email"),
                    CantidadDeUnidadesMovidas = model.Movimiento.CantidadDeUnidadesMovidas
                };

                var movimientoDtoCreated = _servicioMovimientoDeStock.Add(movimientoDto);
                TempData["Exito"] = "Movimiento de stock registrado correctamente";
                return RedirectToAction(nameof(Crear));
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
            }

            ViewBag.Articulos = _servicioArticulo.GetAll().Articulos;
            
            ViewBag.TiposDeMovimiento = _servicioTipoDeMovimiento.GetAll().Tipos;
            return View(model);
        }

        public IActionResult Index(int articuloId, int tipoDeMovimientoId, int pagina = 1, int tamañoPagina = 5)
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return View("NoAutorizado");
            }
            try
            {
                var articulos = _servicioArticulo.GetAll().Articulos;
                var tiposDeMovimiento = _servicioTipoDeMovimiento.GetAll().Tipos;

                var movimientoResponse = new MovimientoDeStockResponseDto();
                int totalDeItems = 0;
                bool busquedaRealizada = false;

                if (articuloId != 0 && tipoDeMovimientoId != 0)
                {
                    movimientoResponse = _servicioMovimientoDeStock.GetMovimientosPorArticuloYTipo(articuloId, tipoDeMovimientoId, (pagina - 1) * tamañoPagina, tamañoPagina);
                    totalDeItems = movimientoResponse.Count;
                    busquedaRealizada = true;
                }

                ViewBag.Articulos = articulos;
                ViewBag.TiposDeMovimiento = tiposDeMovimiento;


                var model = new MovimientoDeStockConsultaViewModel
                {
                    ArticuloId = articuloId,
                    TipoDeMovimientoId = tipoDeMovimientoId,
                    Movimientos = movimientoResponse.Movimientos,
                    Paginacion = new PaginacionModel
                    {
                        PaginaActual = pagina,
                        TamañoPagina = tamañoPagina,
                        TotalDeItems = movimientoResponse.Count
                    },
                    BusquedaRealizada = busquedaRealizada
                };
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
            }
            return View("Index");
        }

        public IActionResult ConsultaPorFechas(DateTime? fechaInicio, DateTime? fechaFin, int pagina = 1, int tamañoPagina = 5)
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return View("NoAutorizado");
            }
            try
            {
                var articulosResponse = new ArticuloResponseDto();
                int totalDeItems = 0;
                bool busquedaRealizada = false;

                if (fechaInicio.HasValue && fechaFin.HasValue)
                {
                    var fechaFinAdjusted = fechaFin.Value.Date.AddDays(1).AddTicks(-1);

                    articulosResponse = _servicioMovimientoDeStock.GetArticuloConMovimientosEnRangoDeFechas(fechaInicio.Value, fechaFinAdjusted, (pagina - 1) * tamañoPagina, tamañoPagina);
                    totalDeItems = articulosResponse.Count;
                    busquedaRealizada = true;
                }

                var model = new ArticuloConMovimientosViewModel
                {
                    FechaInicio = fechaInicio,
                    FechaFin = fechaFin,
                    Articulos = articulosResponse.Articulos,
                    Paginacion = new PaginacionModel
                    {
                        PaginaActual = pagina,
                        TamañoPagina = tamañoPagina,
                        TotalDeItems = totalDeItems
                    },
                    BusquedaRealizada = busquedaRealizada
                };

                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
            }
            return View("Index");
        }

        public IActionResult Resumen()
        {
            if (HttpContext.Session.GetString("email") == null)
            {
                return View("NoAutorizado");
            }
            var resumenResponse = _servicioMovimientoDeStock.GetResumenMovimientos();

            var model = new ResumenMovimientosViewModel
            {
                ResumenPorAño = resumenResponse.ResumenPorAño.Select(r => new MovimientoDeStockResumenViewModel
                {
                    Año = r.Año,
                    Detalles = r.Detalles.Select(d => new DetalleMovimientoViewModel
                    {
                        TipoMovimiento = d.TipoMovimiento,
                        Cantidad = d.Cantidad
                    }),
                    TotalAnual = r.TotalAnual
                })
            };

            return View(model);
        }


    }

}

WebApplication1/Views/Shared/NoAutorizado.cshtml
@model Dto.LoginDto

@{
    ViewData["Title"] = "Credenciales incorrectas";
}

<h1>Acceso denegado</h1>

<h4>Credenciales incorrectas</h4>
<hr />


<div>
    <a asp-controller="Login" asp-action="Index" class="btn btn-primary">Vuelta al login</a>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestion Almacen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("email") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MovimientoDeStock" asp-action="Crear">Registrar Movimiento</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MovimientoDeStock" asp-action="Index">Consultar Movimientos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MovimientoDeStock" asp-action="ConsultaPorFechas">Consultar cambios en articulos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MovimientoDeStock" asp-action="Resumen">Resumen de cantidades movidas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Inicio de Sesion</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gestion Almacen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>